### ISSUE TITLE
Node 12 is out of suport

### ISSUE THREAD

**Issue by KoheiMoroi** [hkusu/review-assign-action#20]
We got a warning message on GitHub Actions like the below:

> Node.js 12 actions are deprecated. For more information see:
> https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 
> Please update the following actions to use Node.js 16: 
> hkusu/review-assign-action@v1

Are you planning on the update?

**Comment by hkusu** [comment]
Thanks for your comment. Released `v1.3.1`. 

https://github.com/hkusu/review-assign-action/releases/tag/v1.3.1

If you use `v1` as follows, the warning should be gone.

```yaml
uses: hkusu/review-assign-action@v1
```
